seed: 42

generate:
  n_samples: 3500
  n_features: 15
  n_informative: 5
  noise: 0.1
  output: data/raw/raw.csv

preprocess:
  test_size: 0.2
  output_train: data/processed/train.csv
  output_test: data/processed/test.csv

train:
  model_output: models/model.joblib
  metrics_output: metrics/train_metrics.json
  n_estimators: 100
  max_depth: 5

evaluate:
  metrics_output: metrics/test_metrics.json
